version: "3"
services:
    mysql:
        image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_USER=dev_user
          - MYSQL_PASSWORD=quieG2phaech4Naichoo8kekizisie2o
          - MYSQL_SERVER_ID=1
        volumes:
#          - ./builds/mount_files/mysql/create_unit_test_db.sql:/docker-entrypoint-initdb.d/create_unit_test_db.sql
          - ./mysql_data:/var/lib/mysql
        command: [
          "--explicit_defaults_for_timestamp=1",
          "--innodb_log_file_size=10M",
          "--performance_schema=OFF",
          "--skip-name-resolve",
          "--skip-host-cache"
        ]
        healthcheck:
          test: [
            "CMD-SHELL",
            "mysql --connect-timeout=1 -u root -ppassword -e \"select 1;\" > /dev/null 2>&1 || exit 1"
          ]
          interval: 30s
          timeout: 10s
          retries: 3
        ports:
          - "${MYSQL_PORT:-3306}:3306"

